### ISSUE TITLE
When supplying channel numbers out of order, dump_midi fails

### ISSUE THREAD

**Issue by nickpeck** [nickpeck/composerstoolkitv2#5]
This causes a bug with dump_midi when channels specified, but not in order
```
mysequencer = Context.get_context().new_sequencer(bpm=35, playback_rate=1, jit=True, dump_midi=True)\
    .add_sequence(tenor, channel_no=3)\
    .add_sequence(alto, channel_no=2)\
    .add_sequence(soprano, channel_no=1)\
    .add_sequence(bass, channel_no=4)\
```

```
2024-05-20 23:05:29,872 - root - INFO - writing midi data to file
Traceback (most recent call last):
  File "examples\26_vocal_polyphony.py", line 127, in <module>
    mysequencer.playback()
  File "c:\users\take1\projects\composerstoolkitv2\src\composerstoolkit\core\sequencer.py", line 173, in playback
    self.scheduler.join(0.1)
  File "c:\users\take1\appdata\local\programs\python\python37\lib\contextlib.py", line 524, in __exit__
    raise exc_details[1]
  File "c:\users\take1\appdata\local\programs\python\python37\lib\contextlib.py", line 509, in __exit__
    if cb(*exc_details):
  File "c:\users\take1\appdata\local\programs\python\python37\lib\contextlib.py", line 377, in _exit_wrapper
    return cm_exit(cm, exc_type, exc, tb)
  File "c:\users\take1\projects\composerstoolkitv2\src\composerstoolkit\core\midicapture.py", line 67, in __exit__
    self._write_midi()
  File "c:\users\take1\projects\composerstoolkitv2\src\composerstoolkit\core\midicapture.py", line 53, in _write_midi
    midifile.addTrackName(channel_no - 1, 0, "Channel {}".format(channel_no))
  File "C:\Users\take1\projects\composerstoolkitv2\lib\site-packages\midiutil\MidiFile.py", line 1123, in addTrackName
    self.tracks[track].addTrackName(self.time_to_ticks(time), trackName,
IndexError: list index out of range

```

**Comment by nickpeck** [comment]
needed to fill in any non-consecutive numbered tracks with a blank track.
also, ensure correct no of tracks supplied in the constructor of midiutil.MIDIFile (including blank tracks)
